### ISSUE TITLE
Minitiouner Steering not working

### ISSUE THREAD

**Issue by f5uii** [F5OEO/datvplutofrm#24]
on Alpha 2908, when clicking on a used channel, no piloting. As indicated by the return of execution of receiver.php, "The JSON extension is not loaded."

PHP JSON extension must be compiled.

**Comment by F5OEO** [comment]
Firmware image is nearly full. I need to remove some components in order to compile PHP JSON. In an other way, a C version of minitiouner steering exists which is very lite.

**Comment by f5uii** [comment]
All right, I understand. I'll try to recode it by handling it in a different way...

**Comment by DG9BFC** [comment]
hello evariste
would it not be easier to get the spectrum from the pluto rx port instead of getting the data from batc?!? ... i guess using the rx of pluto is much better ... no need to have internet (say on a fieldday) ... just split rx port to minituoner AND pluto ... do a "rough scan" on pluto to get the spectrum
all that could be done "slow" (no need to process 8megs bw in realtime)
ever used soft "satsagen" and its specrum scanner with the pluto?? a similar fast scanning could be done for the qo100 datv transponder ... a fast scan on pluto is better in my view as making internet traffic to get the spectrum
and there are cases (portable station) where you just do not have inet

**Comment by f5uii** [comment]
Corrected now in UII2.2 patch 
https://github.com/f5uii/datvplutofrm/commit/d584086fd191caa876c43777b1c6287ba8d882fd
